name: Update exchange rates and trigger new release

permissions:
  contents: write
  pull-requests: read

on:
  workflow_dispatch:

jobs:
  update-exchange-rates:
    name: Update currency exchange rates and trigger new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run Python script
        run: python .github/scripts/update_exchange_rates.py
        env:
          CURRENCY_EXCHANGE_API_KEY: ${{ secrets.CURRENCY_EXCHANGE_API_KEY }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add : |
            - app/src/commonMain/composeResources/files/exchange_rates.json
          message: |
            Update exchange rates
          new_branch: update_exchange_rates
